// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {utils} from '../models';

export function CreateUser(arg1:models.User):Promise<utils.Response>;

export function DeleteUser(arg1:number):Promise<utils.Response>;

export function GetConfig():Promise<utils.Response>;

export function GetUserByID(arg1:number):Promise<utils.Response>;

export function GetUserList(arg1:number,arg2:number):Promise<utils.Response>;

export function Greet(arg1:string):Promise<string>;

export function UpdateUser(arg1:models.User):Promise<utils.Response>;

export function WindowCenter():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WindowSetSize(arg1:number,arg2:number):Promise<void>;
