// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function GetUserList(arg1, arg2) {
  return window['go']['main']['App']['GetUserList'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}

export function WindowCenter() {
  return window['go']['main']['App']['WindowCenter']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WindowSetSize(arg1, arg2) {
  return window['go']['main']['App']['WindowSetSize'](arg1, arg2);
}
